// PPMSeq Simulation Data
// Assigned to window.SIMULATION_DATA for the engine to pick up.

window.SIMULATION_DATA = {
    id: "ppmseq",
    title: "Ultima ppmSeq",
    actors: [
        { id: "wafer", icon: "mdi:disc", color: "text-slate-600", label: "Wafer" },
        { id: "dna-ds", icon: "mdi:dna", color: "text-red-500", label: "Input DNA" },
        { id: "bubble-adapter", icon: "mdi:sync", color: "text-orange-500", label: "Bubble Adapter" },
        { id: "bead", icon: "mdi:circle", color: "text-purple-500", label: "Bead" },
        { id: "droplet", icon: "ph:drop-light", color: "text-blue-500/30", label: "Droplet (1 Bead + 1 DNA)" },
        // Background droplets for limiting dilution visualization
        { id: "bg-droplet-1", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-2", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-3", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-4", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-5", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-6", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-7", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-8", icon: "ph:drop-light", color: "text-blue-500/10", label: "" },
        { id: "bg-droplet-bead-1", icon: "ph:drop-light", color: "text-blue-500/20", label: "" },
        { id: "bg-droplet-bead-2", icon: "ph:drop-light", color: "text-blue-500/20", label: "" },
        { id: "bg-bead-1", icon: "mdi:circle", color: "text-purple-500", label: "" },
        { id: "bg-bead-2", icon: "mdi:circle", color: "text-purple-500", label: "" },
        { id: "bg-dna-1", icon: "mdi:dna", color: "text-red-500", label: "" },
        { id: "bg-dna-2", icon: "mdi:dna", color: "text-red-500", label: "" },
        { id: "bg-dna-3", icon: "mdi:dna", color: "text-red-500", label: "" },
        { id: "clone1", icon: "mdi:dna", color: "text-gray-400", label: "Clones" },
        { id: "clone2", icon: "mdi:dna", color: "text-gray-400", label: "" },
        { id: "clone3", icon: "mdi:dna", color: "text-gray-400", label: "" },
        // Error correction actors
        { id: "bead-dropout", icon: "mdi:circle", color: "text-purple-500", label: "Bead (Strand Dropout)" },
        { id: "clone-dropout-watson", icon: "mdi:dna", color: "text-gray-400", label: "" },
        { id: "dropout-indicator", icon: "mdi:close-circle", color: "text-red-500", label: "" },
        { id: "bead-mismatch", icon: "mdi:circle", color: "text-purple-500", label: "Bead (Base Mismatch)" },
        { id: "clone-mismatch-watson", icon: "mdi:dna", color: "text-gray-400", label: "" },
        { id: "clone-mismatch-crick", icon: "mdi:dna", color: "text-yellow-500", label: "" },
        { id: "mismatch-indicator", icon: "mdi:alert-circle", color: "text-orange-500", label: "" },
        { id: "bead-good", icon: "mdi:circle", color: "text-purple-500", label: "Good Bead" },
        { id: "clone-good-watson", icon: "mdi:dna", color: "text-gray-400", label: "" },
        { id: "clone-good-crick", icon: "mdi:dna", color: "text-gray-400", label: "" },
        { id: "good-indicator", icon: "mdi:check-circle", color: "text-green-500", label: "" },
        { id: "discard-icon", icon: "mdi:delete", color: "text-red-500", label: "Discard" }
    ],
    steps: [
        {
            label: "Bubble Adapter Ligation",
            text: "Custom adapters with a 6-bp poly-A 'bubble' are ligated to DNA.",
            state: {
                "wafer": { x: 120, y: 50, opacity: 0, scale: 2, rotate: 0 },
                "dna-ds": { x: 40, y: 50, opacity: 1, scale: 1.5, rotate: 0 },
                "bubble-adapter": { x: 60, y: 50, opacity: 1, scale: 1.5, rotate: 0 },
                "bead": { x: 120, y: 50, opacity: 0, scale: 0.7, rotate: 0 },
                "droplet": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-1": { x: 20, y: 20, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-2": { x: 80, y: 20, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-3": { x: 20, y: 80, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-4": { x: 80, y: 80, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-5": { x: 35, y: 15, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-6": { x: 65, y: 15, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-7": { x: 35, y: 85, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-8": { x: 65, y: 85, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-bead-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-bead-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-bead-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-bead-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-3": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone1": { x: 52, y: 52, opacity: 0, scale: 0.3, rotate: 0 },
                "clone2": { x: 52, y: 52, opacity: 0, scale: 0.3, rotate: 0 },
                "clone3": { x: 52, y: 52, opacity: 0, scale: 0.3, rotate: 0 },
                // Error correction actors (initially hidden)
                "bead-dropout": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-dropout-watson": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "dropout-indicator": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-mismatch": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-watson": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-crick": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "mismatch-indicator": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-good": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-watson": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-crick": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "good-indicator": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "discard-icon": { x: 50, y: 75, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Limiting Dilution / ePCR",
            text: "Limiting dilution: most droplets are empty, few contain 1 bead + 1 DNA (Poisson).",
            state: {
                "wafer": { x: 120, y: 50, opacity: 0, scale: 2, rotate: 0 },
                "dna-ds": { x: 47, y: 47, opacity: 1, scale: 0.4, rotate: 0 },
                "bubble-adapter": { x: 48, y: 48, opacity: 0, scale: 0.4, rotate: 0 },
                "bead": { x: 53, y: 53, opacity: 1, scale: 0.8, rotate: 0 },
                "droplet": { x: 50, y: 50, opacity: 1, scale: 6, rotate: 0 },
                // Many empty droplets in background
                "bg-droplet-1": { x: 20, y: 20, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-2": { x: 80, y: 20, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-3": { x: 20, y: 80, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-4": { x: 80, y: 80, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-5": { x: 35, y: 15, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-6": { x: 65, y: 15, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-7": { x: 35, y: 85, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-8": { x: 65, y: 85, opacity: 0.6, scale: 3, rotate: 0 },
                // Few droplets with beads only
                "bg-droplet-bead-1": { x: 15, y: 50, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-droplet-bead-2": { x: 85, y: 50, opacity: 0.6, scale: 3, rotate: 0 },
                "bg-bead-1": { x: 15, y: 50, opacity: 0.8, scale: 0.15, rotate: 0 },
                "bg-bead-2": { x: 85, y: 50, opacity: 0.8, scale: 0.15, rotate: 0 },
                // DNA visible in a couple droplets (showing isolated fragments and one bead+DNA pairing)
                "bg-dna-1": { x: 20.5, y: 20.5, opacity: 0.7, scale: 0.12, rotate: 0 },
                "bg-dna-2": { x: 65.5, y: 15.5, opacity: 0.7, scale: 0.12, rotate: 0 },
                "bg-dna-3": { x: 14.5, y: 49.5, opacity: 0.7, scale: 0.12, rotate: 0 },
                "clone1": { x: 52, y: 52, opacity: 0, scale: 0.3, rotate: 0 },
                "clone2": { x: 52, y: 52, opacity: 0, scale: 0.3, rotate: 0 },
                "clone3": { x: 52, y: 52, opacity: 0, scale: 0.3, rotate: 0 },
                // Error correction actors (hidden)
                "bead-dropout": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-dropout-watson": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "dropout-indicator": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-mismatch": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-watson": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-crick": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "mismatch-indicator": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-good": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-watson": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-crick": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "good-indicator": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "discard-icon": { x: 50, y: 75, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Clonal Amp",
            text: "Both Watson and Crick strands amplify onto the SAME bead.",
            state: {
                "wafer": { x: 120, y: 50, opacity: 0, scale: 2, rotate: 0 },
                "dna-ds": { x: 48, y: 48, opacity: 0.5, scale: 0.25, rotate: 0 },
                "bubble-adapter": { x: 48, y: 48, opacity: 0, scale: 0.4, rotate: 0 },
                "bead": { x: 50, y: 50, opacity: 1, scale: 0.5, rotate: 0 },
                "droplet": { x: 50, y: 50, opacity: 1, scale: 6, rotate: 0 },
                // Background droplets fade out during amplification
                "bg-droplet-1": { x: 20, y: 20, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-2": { x: 80, y: 20, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-3": { x: 20, y: 80, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-4": { x: 80, y: 80, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-5": { x: 35, y: 15, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-6": { x: 65, y: 15, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-7": { x: 35, y: 85, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-8": { x: 65, y: 85, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-bead-1": { x: 15, y: 50, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-droplet-bead-2": { x: 85, y: 50, opacity: 0.3, scale: 3, rotate: 0 },
                "bg-bead-1": { x: 15, y: 50, opacity: 0.4, scale: 0.15, rotate: 0 },
                "bg-bead-2": { x: 85, y: 50, opacity: 0.4, scale: 0.15, rotate: 0 },
                "bg-dna-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-3": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone1": { x: 49, y: 49, opacity: 1, scale: 0.2, rotate: 0 },
                "clone2": { x: 51, y: 49, opacity: 1, scale: 0.2, rotate: 0 },
                "clone3": { x: 50, y: 51, opacity: 1, scale: 0.2, rotate: 0 },
                // Error correction actors (hidden)
                "bead-dropout": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-dropout-watson": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "dropout-indicator": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-mismatch": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-watson": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-crick": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "mismatch-indicator": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-good": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-watson": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-crick": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "good-indicator": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "discard-icon": { x: 50, y: 75, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Wafer Flow",
            text: "The bead is loaded onto the open wafer.",
            state: {
                "wafer": { x: 50, y: 50, opacity: 1, scale: 3, rotate: 0 },
                "dna-ds": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bubble-adapter": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bead": { x: 50, y: 50, opacity: 1, scale: 0.7, rotate: 0 },
                "droplet": { x: 50, y: 50, opacity: 0, scale: 10, rotate: 0 },
                "bg-droplet-1": { x: 20, y: 20, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-2": { x: 80, y: 20, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-3": { x: 20, y: 80, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-4": { x: 80, y: 80, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-5": { x: 35, y: 15, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-6": { x: 65, y: 15, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-7": { x: 35, y: 85, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-8": { x: 65, y: 85, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-bead-1": { x: 15, y: 50, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-bead-2": { x: 85, y: 50, opacity: 0, scale: 3, rotate: 0 },
                "bg-bead-1": { x: 15, y: 50, opacity: 0, scale: 0.15, rotate: 0 },
                "bg-bead-2": { x: 85, y: 50, opacity: 0, scale: 0.15, rotate: 0 },
                "bg-dna-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-3": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone1": { x: 49, y: 49, opacity: 1, scale: 0.3, rotate: 0 },
                "clone2": { x: 51, y: 49, opacity: 1, scale: 0.3, rotate: 0 },
                "clone3": { x: 50, y: 51, opacity: 1, scale: 0.3, rotate: 0 },
                // Error correction actors (hidden)
                "bead-dropout": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-dropout-watson": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "dropout-indicator": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-mismatch": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-watson": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-crick": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "mismatch-indicator": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-good": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-watson": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-crick": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "good-indicator": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "discard-icon": { x: 50, y: 75, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Sequencing",
            text: "The sequencer reads both strands simultaneously. Errors average out.",
            state: {
                "wafer": { x: 50, y: 50, opacity: 1, scale: 3, rotate: 90 },
                "dna-ds": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bubble-adapter": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bead": { x: 50, y: 50, opacity: 1, scale: 0.7, rotate: 360 },
                "droplet": { x: 50, y: 50, opacity: 0, scale: 10, rotate: 0 },
                "bg-droplet-1": { x: 20, y: 20, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-2": { x: 80, y: 20, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-3": { x: 20, y: 80, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-4": { x: 80, y: 80, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-5": { x: 35, y: 15, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-6": { x: 65, y: 15, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-7": { x: 35, y: 85, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-8": { x: 65, y: 85, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-bead-1": { x: 15, y: 50, opacity: 0, scale: 3, rotate: 0 },
                "bg-droplet-bead-2": { x: 85, y: 50, opacity: 0, scale: 3, rotate: 0 },
                "bg-bead-1": { x: 15, y: 50, opacity: 0, scale: 0.15, rotate: 0 },
                "bg-bead-2": { x: 85, y: 50, opacity: 0, scale: 0.15, rotate: 0 },
                "bg-dna-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-3": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone1": { x: 49, y: 49, opacity: 1, scale: 0.3, rotate: 360 },
                "clone2": { x: 51, y: 49, opacity: 1, scale: 0.3, rotate: 360 },
                "clone3": { x: 50, y: 51, opacity: 1, scale: 0.3, rotate: 360 },
                // Error correction actors (hidden during sequencing)
                "bead-dropout": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-dropout-watson": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "dropout-indicator": { x: 25, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-mismatch": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-watson": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-mismatch-crick": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "mismatch-indicator": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bead-good": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-watson": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone-good-crick": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "good-indicator": { x: 75, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "discard-icon": { x: 37.5, y: 75, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "QC Analysis",
            text: "Analyzing strand balance and base concordance for each bead.",
            state: {
                "wafer": { x: 50, y: 50, opacity: 0, scale: 3, rotate: 0 },
                "dna-ds": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bubble-adapter": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bead": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "droplet": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-1": { x: 20, y: 20, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-2": { x: 80, y: 20, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-3": { x: 20, y: 80, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-4": { x: 80, y: 80, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-5": { x: 35, y: 15, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-6": { x: 65, y: 15, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-7": { x: 35, y: 85, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-8": { x: 65, y: 85, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-bead-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-bead-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-bead-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-bead-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-3": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone1": { x: 49, y: 49, opacity: 0, scale: 0.3, rotate: 0 },
                "clone2": { x: 51, y: 49, opacity: 0, scale: 0.3, rotate: 0 },
                "clone3": { x: 50, y: 51, opacity: 0, scale: 0.3, rotate: 0 },
                // Showing all three beads with QC results
                "bead-dropout": { x: 25, y: 50, opacity: 1, scale: 1.2, rotate: 0 },
                "clone-dropout-watson": { x: 25, y: 50, opacity: 1, scale: 0.5, rotate: 0 },
                "dropout-indicator": { x: 25, y: 62, opacity: 1, scale: 0.8, rotate: 0 },
                "bead-mismatch": { x: 50, y: 50, opacity: 1, scale: 1.2, rotate: 0 },
                "clone-mismatch-watson": { x: 49, y: 49, opacity: 1, scale: 0.5, rotate: 0 },
                "clone-mismatch-crick": { x: 51, y: 51, opacity: 1, scale: 0.5, rotate: 0 },
                "mismatch-indicator": { x: 50, y: 62, opacity: 1, scale: 0.8, rotate: 0 },
                "bead-good": { x: 75, y: 50, opacity: 1, scale: 1.2, rotate: 0 },
                "clone-good-watson": { x: 74, y: 49, opacity: 1, scale: 0.5, rotate: 0 },
                "clone-good-crick": { x: 76, y: 51, opacity: 1, scale: 0.5, rotate: 0 },
                "good-indicator": { x: 75, y: 62, opacity: 1, scale: 0.8, rotate: 0 },
                "discard-icon": { x: 37.5, y: 75, opacity: 1, scale: 1.5, rotate: 0 }
            }
        },
        {
            label: "Error Correction",
            text: "Discarding beads with strand dropout or base mismatches. Only balanced pairs pass QC.",
            state: {
                "wafer": { x: 50, y: 50, opacity: 0, scale: 3, rotate: 0 },
                "dna-ds": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bubble-adapter": { x: 20, y: 50, opacity: 0, scale: 0.2, rotate: 0 },
                "bead": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "droplet": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-1": { x: 20, y: 20, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-2": { x: 80, y: 20, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-3": { x: 20, y: 80, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-4": { x: 80, y: 80, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-5": { x: 35, y: 15, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-6": { x: 65, y: 15, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-7": { x: 35, y: 85, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-8": { x: 65, y: 85, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-bead-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-droplet-bead-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-bead-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-bead-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-1": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-2": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "bg-dna-3": { x: 15, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "clone1": { x: 49, y: 49, opacity: 0, scale: 0.3, rotate: 0 },
                "clone2": { x: 51, y: 49, opacity: 0, scale: 0.3, rotate: 0 },
                "clone3": { x: 50, y: 51, opacity: 0, scale: 0.3, rotate: 0 },
                // Error beads moving to discard and fading out
                "bead-dropout": { x: 37.5, y: 75, opacity: 0, scale: 0.4, rotate: 0 },
                "clone-dropout-watson": { x: 37.5, y: 75, opacity: 0, scale: 0.3, rotate: 0 },
                "dropout-indicator": { x: 37.5, y: 75, opacity: 0, scale: 0.4, rotate: 0 },
                "bead-mismatch": { x: 37.5, y: 75, opacity: 0, scale: 0.4, rotate: 0 },
                "clone-mismatch-watson": { x: 37.5, y: 75, opacity: 0, scale: 0.3, rotate: 0 },
                "clone-mismatch-crick": { x: 37.5, y: 75, opacity: 0, scale: 0.3, rotate: 0 },
                "mismatch-indicator": { x: 37.5, y: 75, opacity: 0, scale: 0.4, rotate: 0 },
                // Good bead remains visible and centered
                "bead-good": { x: 50, y: 50, opacity: 1, scale: 1.2, rotate: 0 },
                "clone-good-watson": { x: 49, y: 49, opacity: 1, scale: 0.5, rotate: 0 },
                "clone-good-crick": { x: 51, y: 51, opacity: 1, scale: 0.5, rotate: 0 },
                "good-indicator": { x: 50, y: 62, opacity: 1, scale: 1.0, rotate: 0 },
                // Discard icon fades after discarding
                "discard-icon": { x: 37.5, y: 75, opacity: 0.3, scale: 2, rotate: 0 }
            }
        }
    ]
};
