// UDSeq Simulation Data
// Registered with the engine using registerSimulation().

window.registerSimulation({
    id: "udseq",
    title: "UDSeq",
    actors: [
        { id: "dna-input", icon: "mdi:dna", color: "text-blue-500", label: "Input DNA" },
        { id: "fragmentase", icon: "mdi:flask-outline", color: "text-purple-500", label: "Fragmentase" },
        { id: "fragment1", icon: "mdi:dna", color: "text-blue-400", label: "" },
        { id: "fragment2", icon: "mdi:dna", color: "text-blue-400", label: "" },
        { id: "fragment3", icon: "mdi:dna", color: "text-blue-400", label: "" },
        { id: "umi-adapter1", icon: "mdi:link-variant", color: "text-green-500", label: "UMI Adapter" },
        { id: "umi-adapter2", icon: "mdi:link-variant", color: "text-green-500", label: "" },
        { id: "ligated-fragment", icon: "mdi:dna", color: "text-blue-500", label: "UMI-Ligated Fragment" },
        { id: "qpcr-icon", icon: "mdi:chart-line", color: "text-orange-500", label: "qPCR Quantification" },
        { id: "measurement", icon: "mdi:ruler", color: "text-orange-400", label: "" },
        { id: "pcr-icon", icon: "mdi:dna", color: "text-gray-400", label: "PCR" },
        { id: "amplicon1", icon: "mdi:dna", color: "text-gray-300", label: "" },
        { id: "amplicon2", icon: "mdi:dna", color: "text-gray-300", label: "" },
        { id: "amplicon3", icon: "mdi:dna", color: "text-gray-300", label: "" },
        { id: "watson-strand", icon: "mdi:dna", color: "text-blue-500", label: "Watson Strand" },
        { id: "crick-strand", icon: "mdi:dna", color: "text-orange-500", label: "Crick Strand" },
        { id: "sequencer", icon: "mdi:chip", color: "text-indigo-500", label: "Sequencer" },
        { id: "watson-read", icon: "mdi:text", color: "text-blue-400", label: "Watson Read" },
        { id: "crick-read", icon: "mdi:text", color: "text-orange-400", label: "Crick Read" },
        { id: "error-watson", icon: "mdi:alert-circle", color: "text-red-500", label: "" },
        { id: "error-crick", icon: "mdi:alert-circle", color: "text-red-500", label: "" },
        { id: "consensus", icon: "mdi:check-circle", color: "text-green-500", label: "Duplex Consensus" },
        { id: "final-sequence", icon: "mdi:text-box", color: "text-green-600", label: "Error-Free Sequence" }
    ],
    steps: [
        {
            label: "Input DNA",
            text: "Starting with genomic DNA from cells, tissue, or other biological samples.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 1, scale: 2, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "fragment1": { x: 30, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "fragment2": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "fragment3": { x: 70, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter1": { x: 30, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter2": { x: 70, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "qpcr-icon": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "measurement": { x: 70, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "watson-strand": { x: 50, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-strand": { x: 50, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "sequencer": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "watson-read": { x: 35, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-read": { x: 35, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "error-watson": { x: 45, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 55, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Random Fragmentation",
            text: "DNA is randomly fragmented using Fragmentase or UltraShear for universal genome coverage.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0.3, scale: 1.5, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 1, scale: 1.5, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 1, scale: 1.2, rotate: -15 },
                "fragment2": { x: 50, y: 55, opacity: 1, scale: 1.2, rotate: 5 },
                "fragment3": { x: 70, y: 55, opacity: 1, scale: 1.2, rotate: 10 },
                "umi-adapter1": { x: 30, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter2": { x: 70, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "qpcr-icon": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "measurement": { x: 70, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "watson-strand": { x: 50, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-strand": { x: 50, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "sequencer": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "watson-read": { x: 35, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-read": { x: 35, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "error-watson": { x: 45, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 55, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "UMI Adapter Ligation",
            text: "High-efficiency UMI adapters are ligated using xGen cfDNA & FFPE DNA Kit (works with as little as 100 pg DNA).",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 1, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 0.3, scale: 0.8, rotate: 0 },
                "fragment2": { x: 50, y: 55, opacity: 0.3, scale: 0.8, rotate: 0 },
                "fragment3": { x: 70, y: 55, opacity: 0.3, scale: 0.8, rotate: 0 },
                "umi-adapter1": { x: 35, y: 50, opacity: 1, scale: 1.2, rotate: 0 },
                "umi-adapter2": { x: 65, y: 50, opacity: 1, scale: 1.2, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 1, scale: 1.5, rotate: 0 },
                "qpcr-icon": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "measurement": { x: 70, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "watson-strand": { x: 50, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-strand": { x: 50, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "sequencer": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "watson-read": { x: 35, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-read": { x: 35, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "error-watson": { x: 45, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 55, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "qPCR Quantification",
            text: "Precise quantification of UMI-ligated molecules using qPCR ensures optimal PCR input and reduces artifacts.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment3": { x: 70, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter1": { x: 35, y: 50, opacity: 0.3, scale: 0.8, rotate: 0 },
                "umi-adapter2": { x: 65, y: 50, opacity: 0.3, scale: 0.8, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 1, scale: 1.2, rotate: 0 },
                "qpcr-icon": { x: 50, y: 25, opacity: 1, scale: 1.8, rotate: 0 },
                "measurement": { x: 65, y: 35, opacity: 1, scale: 1.2, rotate: 0 },
                "pcr-icon": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "watson-strand": { x: 50, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-strand": { x: 50, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "sequencer": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "watson-read": { x: 35, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-read": { x: 35, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "error-watson": { x: 45, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 55, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "PCR Amplification",
            text: "Controlled PCR amplification with precise input (e.g., 0.2 fmol) maintains single-molecule fidelity.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment3": { x: 70, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter1": { x: 35, y: 50, opacity: 0.3, scale: 0.8, rotate: 0 },
                "umi-adapter2": { x: 65, y: 50, opacity: 0.3, scale: 0.8, rotate: 0 },
                "ligated-fragment": { x: 50, y: 45, opacity: 1, scale: 1.2, rotate: 0 },
                "qpcr-icon": { x: 50, y: 25, opacity: 0.3, scale: 1.2, rotate: 0 },
                "measurement": { x: 65, y: 35, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 25, opacity: 1, scale: 1.5, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 1, scale: 0.8, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 1, scale: 0.8, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 1, scale: 0.8, rotate: 0 },
                "watson-strand": { x: 50, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-strand": { x: 50, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "sequencer": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "watson-read": { x: 35, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-read": { x: 35, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "error-watson": { x: 45, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 55, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Strand Separation",
            text: "DNA strands are separated for duplex sequencing. Both Watson and Crick strands will be sequenced independently.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment3": { x: 70, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter1": { x: 35, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter2": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 0.2, scale: 1, rotate: 0 },
                "qpcr-icon": { x: 50, y: 25, opacity: 0, scale: 0, rotate: 0 },
                "measurement": { x: 65, y: 35, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 25, opacity: 0, scale: 1, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0.5, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0.5, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0.5, rotate: 0 },
                "watson-strand": { x: 50, y: 35, opacity: 1, scale: 1.5, rotate: 0 },
                "crick-strand": { x: 50, y: 65, opacity: 1, scale: 1.5, rotate: 0 },
                "sequencer": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "watson-read": { x: 35, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "crick-read": { x: 35, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "error-watson": { x: 45, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 55, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Duplex Sequencing",
            text: "Both strands are sequenced independently. Sequencing errors may occur randomly on each strand.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment3": { x: 70, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter1": { x: 35, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter2": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "qpcr-icon": { x: 50, y: 25, opacity: 0, scale: 0, rotate: 0 },
                "measurement": { x: 65, y: 35, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 25, opacity: 0, scale: 0, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "watson-strand": { x: 30, y: 35, opacity: 1, scale: 1.2, rotate: 0 },
                "crick-strand": { x: 30, y: 65, opacity: 1, scale: 1.2, rotate: 0 },
                "sequencer": { x: 70, y: 50, opacity: 1, scale: 2, rotate: 0 },
                "watson-read": { x: 60, y: 35, opacity: 1, scale: 1, rotate: 0 },
                "crick-read": { x: 60, y: 65, opacity: 1, scale: 1, rotate: 0 },
                "error-watson": { x: 68, y: 35, opacity: 1, scale: 0.8, rotate: 0 },
                "error-crick": { x: 68, y: 65, opacity: 1, scale: 0.8, rotate: 0 },
                "consensus": { x: 85, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Duplex Consensus",
            text: "Both strand reads are combined. Errors present in only one strand are corrected, achieving ~2.5×10⁻⁹ error rate.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment3": { x: 70, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter1": { x: 35, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter2": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "qpcr-icon": { x: 50, y: 25, opacity: 0, scale: 0, rotate: 0 },
                "measurement": { x: 65, y: 35, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 25, opacity: 0, scale: 0, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "watson-strand": { x: 30, y: 35, opacity: 0.3, scale: 1, rotate: 0 },
                "crick-strand": { x: 30, y: 65, opacity: 0.3, scale: 1, rotate: 0 },
                "sequencer": { x: 70, y: 50, opacity: 0.5, scale: 1.5, rotate: 0 },
                "watson-read": { x: 50, y: 40, opacity: 0.5, scale: 0.8, rotate: 0 },
                "crick-read": { x: 50, y: 60, opacity: 0.5, scale: 0.8, rotate: 0 },
                "error-watson": { x: 58, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 58, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 70, y: 50, opacity: 1, scale: 1.5, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 }
            }
        },
        {
            label: "Error-Free Sequence",
            text: "Ultra-accurate sequence with error rate ~2.5×10⁻⁹, enabling detection of rare somatic mutations from as little as 100 pg DNA.",
            state: {
                "dna-input": { x: 50, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "fragmentase": { x: 50, y: 30, opacity: 0, scale: 0, rotate: 0 },
                "fragment1": { x: 30, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "fragment3": { x: 70, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter1": { x: 35, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "umi-adapter2": { x: 65, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "ligated-fragment": { x: 50, y: 50, opacity: 0, scale: 0, rotate: 0 },
                "qpcr-icon": { x: 50, y: 25, opacity: 0, scale: 0, rotate: 0 },
                "measurement": { x: 65, y: 35, opacity: 0, scale: 0, rotate: 0 },
                "pcr-icon": { x: 50, y: 25, opacity: 0, scale: 0, rotate: 0 },
                "amplicon1": { x: 40, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon2": { x: 50, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "amplicon3": { x: 60, y: 55, opacity: 0, scale: 0, rotate: 0 },
                "watson-strand": { x: 30, y: 35, opacity: 0, scale: 0.5, rotate: 0 },
                "crick-strand": { x: 30, y: 65, opacity: 0, scale: 0.5, rotate: 0 },
                "sequencer": { x: 70, y: 50, opacity: 0, scale: 1, rotate: 0 },
                "watson-read": { x: 50, y: 40, opacity: 0, scale: 0.5, rotate: 0 },
                "crick-read": { x: 50, y: 60, opacity: 0, scale: 0.5, rotate: 0 },
                "error-watson": { x: 58, y: 40, opacity: 0, scale: 0, rotate: 0 },
                "error-crick": { x: 58, y: 60, opacity: 0, scale: 0, rotate: 0 },
                "consensus": { x: 50, y: 50, opacity: 0.3, scale: 1.2, rotate: 0 },
                "final-sequence": { x: 50, y: 50, opacity: 1, scale: 2.5, rotate: 0 }
            }
        }
    ]
});
